## GET all post
##############
GET http://localhost:8080/feed/posts
###
POST  http://localhost:8080/feed/post
Content-Type: application/json

{
    "title":"Client REST API-with mongoose-v2",
    "imageUrl":"images/part-one/CROS.PNG",
    "content":"The Reust sended by Client RESTAPI after connect with package mongoose-v2"
}